/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.witelokk.musicapp.api.models

import com.witelokk.musicapp.api.models.ArtistSummary

import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

/**
 * 
 *
 * @param count 
 * @param artists 
 * @param names 
 */
@Serializable

data class ArtistsSummary (

    @SerialName(value = "count") @Required val count: kotlin.Int,

    @SerialName(value = "artists") @Required val artists: kotlin.collections.List<ArtistSummary>,

    @SerialName(value = "names") @Required val names: kotlin.String

) {


}

