/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.witelokk.musicapp.api.models


import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

/**
 * 
 *
 * @param eventType 
 * @param songId 
 * @param clientEventId 
 * @param positionSeconds 
 * @param durationSeconds 
 * @param percentPlayed 
 * @param source 
 * @param contextType 
 * @param contextId 
 */
@Serializable

data class CreateUserEventRequest (

    @SerialName(value = "event_type") @Required val eventType: CreateUserEventRequest.EventType,

    @SerialName(value = "song_id") @Required val songId: kotlin.String,

    @SerialName(value = "client_event_id") @Required val clientEventId: kotlin.String,

    @SerialName(value = "position_seconds") val positionSeconds: kotlin.Int? = null,

    @SerialName(value = "duration_seconds") val durationSeconds: kotlin.Int? = null,

    @SerialName(value = "percent_played") val percentPlayed: kotlin.Double? = null,

    @SerialName(value = "source") val source: kotlin.String? = null,

    @SerialName(value = "context_type") val contextType: CreateUserEventRequest.ContextType? = null,

    @SerialName(value = "context_id") val contextId: kotlin.String? = null

) {

    /**
     * 
     *
     * Values: song_play,song_skip,song_complete
     */
    @Serializable
    enum class EventType(val value: kotlin.String) {
        @SerialName(value = "song_play") song_play("song_play"),
        @SerialName(value = "song_skip") song_skip("song_skip"),
        @SerialName(value = "song_complete") song_complete("song_complete");
    }
    /**
     * 
     *
     * Values: playlist,release,artist,queue,recommendations
     */
    @Serializable
    enum class ContextType(val value: kotlin.String) {
        @SerialName(value = "playlist") playlist("playlist"),
        @SerialName(value = "release") release("release"),
        @SerialName(value = "artist") artist("artist"),
        @SerialName(value = "queue") queue("queue"),
        @SerialName(value = "recommendations") recommendations("recommendations");
    }

}

