/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.witelokk.musicapp.api.models

import com.witelokk.musicapp.api.models.GetTokensByAppleTokenRequest
import com.witelokk.musicapp.api.models.GetTokensByCodeRequest
import com.witelokk.musicapp.api.models.GetTokensByGoogleTokenRequest
import com.witelokk.musicapp.api.models.GetTokensByRefreshTokenRequest

import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*
import kotlinx.serialization.json.JsonClassDiscriminator

/**
 * Request to obtain tokens.
 *
 * @param grantType Grant type to use.
 * @param email User email.
 * @param code Verification code received by email.
 * @param refreshToken Refresh token.
 * @param googleToken Reserved for future Google auth integration.
 * @param appleToken Reserved for future Apple auth integration.
 */
@Serializable


@OptIn(ExperimentalSerializationApi::class)
@JsonClassDiscriminator(discriminator = "grantType")
sealed class GetTokensRequest {

    /* Grant type to use. */
    @SerialName(value = "grant_type") @Required abstract val grantType: GetTokensRequest.GrantType
    /* User email. */
    @SerialName(value = "email") @Required abstract val email: kotlin.String
    /* Verification code received by email. */
    @SerialName(value = "code") @Required abstract val code: kotlin.String
    /* Refresh token. */
    @SerialName(value = "refresh_token") @Required abstract val refreshToken: kotlin.String
    /* Reserved for future Google auth integration. */
    @SerialName(value = "google_token") @Required abstract val googleToken: kotlin.String
    /* Reserved for future Apple auth integration. */
    @SerialName(value = "apple_token") @Required abstract val appleToken: kotlin.String
    /**
     * Grant type to use.
     *
     * Values: apple_token
     */
    @Serializable
    enum class GrantType(val value: kotlin.String) {
        @SerialName(value = "apple_token") apple_token("apple_token");
    }

}

