/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.witelokk.musicapp.api.models


import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

/**
 * 
 *
 * @param grantType Grant type to use.
 * @param appleToken Reserved for future Apple auth integration.
 */
@Serializable

data class GetTokensByAppleTokenRequest (

    /* Grant type to use. */
    @SerialName(value = "grant_type") @Required val grantType: GetTokensByAppleTokenRequest.GrantType,

    /* Reserved for future Apple auth integration. */
    @SerialName(value = "apple_token") @Required val appleToken: kotlin.String

) {

    /**
     * Grant type to use.
     *
     * Values: apple_token
     */
    @Serializable
    enum class GrantType(val value: kotlin.String) {
        @SerialName(value = "apple_token") apple_token("apple_token");
    }

}

