/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.witelokk.musicapp.api.models


import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

/**
 * 
 *
 * @param grantType Grant type to use.
 * @param googleToken Reserved for future Google auth integration.
 */
@Serializable

data class GetTokensByGoogleTokenRequest (

    /* Grant type to use. */
    @SerialName(value = "grant_type") @Required val grantType: GetTokensByGoogleTokenRequest.GrantType,

    /* Reserved for future Google auth integration. */
    @SerialName(value = "google_token") @Required val googleToken: kotlin.String

) {

    /**
     * Grant type to use.
     *
     * Values: google_token
     */
    @Serializable
    enum class GrantType(val value: kotlin.String) {
        @SerialName(value = "google_token") google_token("google_token");
    }

}

