/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.witelokk.musicapp.api.models


import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

/**
 * 
 *
 * @param grantType Grant type to use.
 * @param refreshToken Refresh token.
 */
@Serializable

data class GetTokensByRefreshTokenRequest (

    /* Grant type to use. */
    @SerialName(value = "grant_type") @Required val grantType: GetTokensByRefreshTokenRequest.GrantType,

    /* Refresh token. */
    @SerialName(value = "refresh_token") @Required val refreshToken: kotlin.String

) {

    /**
     * Grant type to use.
     *
     * Values: refresh_token
     */
    @Serializable
    enum class GrantType(val value: kotlin.String) {
        @SerialName(value = "refresh_token") refresh_token("refresh_token");
    }

}

