/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.witelokk.musicapp.api.models


import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

/**
 * 
 *
 * @param grantType Grant type to use.
 * @param email User email.
 * @param code Verification code received by email.
 */
@Serializable

data class GetTokensByCodeRequest (

    /* Grant type to use. */
    @SerialName(value = "grant_type") @Required val grantType: GetTokensByCodeRequest.GrantType,

    /* User email. */
    @SerialName(value = "email") @Required val email: kotlin.String,

    /* Verification code received by email. */
    @SerialName(value = "code") @Required val code: kotlin.String

) {

    /**
     * Grant type to use.
     *
     * Values: code
     */
    @Serializable
    enum class GrantType(val value: kotlin.String) {
        @SerialName(value = "code") code("code");
    }

}

