/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.witelokk.musicapp.api.models

import com.witelokk.musicapp.api.models.ArtistSummary
import com.witelokk.musicapp.api.models.PlaylistSummary
import com.witelokk.musicapp.api.models.ReleaseSummary

import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

/**
 * 
 *
 * @param type Type of the home feed item.
 * @param release 
 * @param playlist 
 * @param artist 
 */
@Serializable

data class HomeFeedItem (

    /* Type of the home feed item. */
    @SerialName(value = "type") @Required val type: HomeFeedItem.Type,

    @SerialName(value = "release") val release: ReleaseSummary? = null,

    @SerialName(value = "playlist") val playlist: PlaylistSummary? = null,

    @SerialName(value = "artist") val artist: ArtistSummary? = null

) {

    /**
     * Type of the home feed item.
     *
     * Values: release,playlist,artist,favorites
     */
    @Serializable
    enum class Type(val value: kotlin.String) {
        @SerialName(value = "release") release("release"),
        @SerialName(value = "playlist") playlist("playlist"),
        @SerialName(value = "artist") artist("artist"),
        @SerialName(value = "favorites") favorites("favorites");
    }

}

