/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.witelokk.musicapp.api.models

import kotlinx.serialization.Required
import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable

/**
 * 
 *
 * @param titles
 * @param releases 
 */
@Serializable
data class HomeScreenLayoutCompanionSection (

    @SerialName(value = "titles") @Required val titles: kotlin.collections.Map<kotlin.String, kotlin.String>,

    @SerialName(value = "releases") @Required val releases: Releases

) {
    fun titleFor(language: String): String {
        return titles[language]
            ?: titles[language.substringBefore('-')]
            ?: titles["en"]
            ?: titles["ru"]
            ?: titles.values.firstOrNull()
            ?: ""
    }

}
