/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.witelokk.musicapp.api.models

import com.witelokk.musicapp.api.models.ReleaseSummaryList

import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

/**
 * 
 *
 * @param titles 
 * @param releases 
 */
@Serializable

data class HomeScreenSection (

    @SerialName(value = "titles") @Required val titles: kotlin.collections.Map<kotlin.String, kotlin.String>,

    @SerialName(value = "releases") @Required val releases: ReleaseSummaryList

) {


}

