/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.witelokk.musicapp.api.models

import com.witelokk.musicapp.api.models.ArtistList
import com.witelokk.musicapp.api.models.HomeScreenSection
import com.witelokk.musicapp.api.models.PlaylistsSummary

import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

/**
 * 
 *
 * @param playlists 
 * @param followedArtists 
 * @param sections 
 */
@Serializable

data class HomeFeed (

    @SerialName(value = "playlists") @Required val playlists: PlaylistsSummary,

    @SerialName(value = "followedArtists") @Required val followedArtists: ArtistList,

    @SerialName(value = "sections") @Required val sections: kotlin.collections.List<HomeScreenSection>

) {


}

