/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.witelokk.musicapp.api.models

import com.witelokk.musicapp.api.models.Releases

import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

/**
 * 
 *
 * @param title 
 * @param titleRu 
 * @param releases 
 */
@Serializable

data class HomeScreenLayoutCompanionSection (

    @SerialName(value = "title") @Required val title: kotlin.String,

    @SerialName(value = "title_ru") @Required val titleRu: kotlin.String,

    @SerialName(value = "releases") @Required val releases: Releases

) {


}

