/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.witelokk.musicapp.api.models

import com.witelokk.musicapp.api.models.ReleaseSummary

import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

/**
 * 
 *
 * @param count 
 * @param releases 
 */
@Serializable

data class ReleaseSummaryList (

    @SerialName(value = "count") @Required val count: kotlin.Int,

    @SerialName(value = "releases") @Required val releases: kotlin.collections.List<ReleaseSummary>

) {


}

