/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.witelokk.musicapp.api.models


import kotlinx.serialization.*

/**
 * 
 *
 * Values: single,album,ep
 */
@Serializable
enum class ReleaseType(val value: kotlin.String) {

    @SerialName(value = "single")
    single("single"),

    @SerialName(value = "album")
    album("album"),

    @SerialName(value = "ep")
    ep("ep");

    /**
     * Override [toString()] to avoid using the enum variable name as the value, and instead use
     * the actual value defined in the API spec file.
     *
     * This solves a problem when the variable name and its value are different, and ensures that
     * the client sends the correct enum values to the server always.
     */
    override fun toString(): kotlin.String = value

    companion object {
        /**
         * Converts the provided [data] to a [String] on success, null otherwise.
         */
        fun encode(data: kotlin.Any?): kotlin.String? = if (data is ReleaseType) "$data" else null

        /**
         * Returns a valid [ReleaseType] for [data], null otherwise.
         */
        fun decode(data: kotlin.Any?): ReleaseType? = data?.let {
          val normalizedData = "$it".lowercase()
          entries.firstOrNull { value ->
            it == value || normalizedData == "$value".lowercase()
          }
        }
    }
}

