/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.witelokk.musicapp.api.models

import kotlinx.serialization.Required
import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable

/**
 * 
 *
 * @param count 
 * @param releases 
 */
@Serializable

data class Releases (

    @SerialName(value = "count") @Required val count: kotlin.Int,

    @SerialName(value = "releases") @Required val releases: kotlin.collections.List<ReleaseSummary>

) {


}
