/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.witelokk.musicapp.api.models

import com.witelokk.musicapp.api.models.ArtistSummary
import com.witelokk.musicapp.api.models.PlaylistSummary
import com.witelokk.musicapp.api.models.ReleaseSummary
import com.witelokk.musicapp.api.models.Song

import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

/**
 * 
 *
 * @param type Type of the search result.
 * @param song 
 * @param release 
 * @param artist 
 * @param playlist 
 */
@Serializable

data class SearchResultItem (

    /* Type of the search result. */
    @SerialName(value = "type") @Required val type: SearchResultItem.Type,

    @SerialName(value = "song") val song: Song? = null,

    @SerialName(value = "release") val release: ReleaseSummary? = null,

    @SerialName(value = "artist") val artist: ArtistSummary? = null,

    @SerialName(value = "playlist") val playlist: PlaylistSummary? = null

) {

    /**
     * Type of the search result.
     *
     * Values: song,release,artist,playlist
     */
    @Serializable
    enum class Type(val value: kotlin.String) {
        @SerialName(value = "song") song("song"),
        @SerialName(value = "release") release("release"),
        @SerialName(value = "artist") artist("artist"),
        @SerialName(value = "playlist") playlist("playlist");
    }

}

