/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.witelokk.musicapp.api.models

import com.witelokk.musicapp.api.models.SearchResultItem

import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

/**
 * 
 *
 * @param query 
 * @param page 
 * @param limit 
 * @param total 
 * @param results 
 */
@Serializable

data class SearchResult (

    @SerialName(value = "query") @Required val query: kotlin.String,

    @SerialName(value = "page") @Required val page: kotlin.Int,

    @SerialName(value = "limit") @Required val limit: kotlin.Int,

    @SerialName(value = "total") @Required val total: kotlin.Int,

    @SerialName(value = "results") @Required val results: kotlin.collections.List<SearchResultItem>

) {


}

