/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.witelokk.musicapp.api.models

import com.witelokk.musicapp.api.models.ArtistSummary

import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

/**
 * 
 *
 * @param id 
 * @param name 
 * @param isFavorite 
 * @param durationSeconds 
 * @param artists 
 * @param streamUrl 
 * @param coverUrl 
 */
@Serializable

data class Song (

    @SerialName(value = "id") @Required val id: kotlin.String,

    @SerialName(value = "name") @Required val name: kotlin.String,

    @SerialName(value = "is_favorite") @Required val isFavorite: kotlin.Boolean,

    @SerialName(value = "duration_seconds") @Required val durationSeconds: kotlin.Int,

    @SerialName(value = "artists") @Required val artists: kotlin.collections.List<ArtistSummary>,

    @SerialName(value = "stream_url") @Required val streamUrl: kotlin.String,

    @SerialName(value = "cover_url") val coverUrl: kotlin.String? = null

) {


}

