/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.witelokk.musicapp.api.models


import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

/**
 * 
 *
 * @param accessToken 
 * @param refreshToken 
 */
@Serializable

data class TokensResponse (

    @SerialName(value = "access_token") @Required val accessToken: kotlin.String,

    @SerialName(value = "refresh_token") @Required val refreshToken: kotlin.String

) {


}

