/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.witelokk.musicapp.api.apis

import com.witelokk.musicapp.api.models.ComwitelokkmusicmodelsAddFavoriteSongRequest
import com.witelokk.musicapp.api.models.ComwitelokkmusicmodelsFailureResponse
import com.witelokk.musicapp.api.models.ComwitelokkmusicmodelsRemoveFavoriteSongRequest

import com.witelokk.musicapp.api.infrastructure.*
import io.ktor.client.HttpClientConfig
import io.ktor.client.request.forms.formData
import io.ktor.client.engine.HttpClientEngine
import io.ktor.http.ParametersBuilder

    open class FavoritesApi(
    baseUrl: String = ApiClient.BASE_URL,
    httpClientEngine: HttpClientEngine? = null,
    httpClientConfig: ((HttpClientConfig<*>) -> Unit)? = null,
    ) : ApiClient(
        baseUrl,
        httpClientEngine,
        httpClientConfig,
    ) {

        /**
        * 
        * Remove favorite song
         * @param comwitelokkmusicmodelsRemoveFavoriteSongRequest  (optional)
         * @return void
        */
        open suspend fun favoritesDelete(comwitelokkmusicmodelsRemoveFavoriteSongRequest: ComwitelokkmusicmodelsRemoveFavoriteSongRequest?): HttpResponse<Unit> {

            val localVariableAuthNames = listOf<String>("Authorization")

            val localVariableBody = comwitelokkmusicmodelsRemoveFavoriteSongRequest

            val localVariableQuery = mutableMapOf<String, List<String>>()

            val localVariableHeaders = mutableMapOf<String, String>()

            val localVariableConfig = RequestConfig<kotlin.Any?>(
            RequestMethod.DELETE,
            "/favorites",
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = true,
            )

            return jsonRequest(
            localVariableConfig,
            localVariableBody,
            localVariableAuthNames
            ).wrap()
            }

        /**
        * 
        * Get favorite songs
         * @return kotlin.Any
        */
            @Suppress("UNCHECKED_CAST")
        open suspend fun favoritesGet(): HttpResponse<kotlin.Any> {

            val localVariableAuthNames = listOf<String>("Authorization")

            val localVariableBody = 
                    io.ktor.client.utils.EmptyContent

            val localVariableQuery = mutableMapOf<String, List<String>>()

            val localVariableHeaders = mutableMapOf<String, String>()

            val localVariableConfig = RequestConfig<kotlin.Any?>(
            RequestMethod.GET,
            "/favorites",
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = true,
            )

            return request(
            localVariableConfig,
            localVariableBody,
            localVariableAuthNames
            ).wrap()
            }

        /**
        * 
        * Add favorite song
         * @param comwitelokkmusicmodelsAddFavoriteSongRequest  (optional)
         * @return void
        */
        open suspend fun favoritesPost(comwitelokkmusicmodelsAddFavoriteSongRequest: ComwitelokkmusicmodelsAddFavoriteSongRequest?): HttpResponse<Unit> {

            val localVariableAuthNames = listOf<String>("Authorization")

            val localVariableBody = comwitelokkmusicmodelsAddFavoriteSongRequest

            val localVariableQuery = mutableMapOf<String, List<String>>()

            val localVariableHeaders = mutableMapOf<String, String>()

            val localVariableConfig = RequestConfig<kotlin.Any?>(
            RequestMethod.POST,
            "/favorites",
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = true,
            )

            return jsonRequest(
            localVariableConfig,
            localVariableBody,
            localVariableAuthNames
            ).wrap()
            }

        }
