/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.witelokk.musicapp.api.models

import com.witelokk.musicapp.api.models.ComwitelokkmusicmodelsShortArtist
import com.witelokk.musicapp.api.models.ComwitelokkmusicmodelsShortPlaylist
import com.witelokk.musicapp.api.models.ComwitelokkmusicmodelsShortRelease
import com.witelokk.musicapp.api.models.ComwitelokkmusicmodelsSong

import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * 
 *
 * @param type 
 * @param song 
 * @param release 
 * @param artist 
 * @param playlist 
 */
@Serializable

data class ComwitelokkmusicmodelsSearchResultItem (

    @SerialName(value = "type")
    val type: kotlin.String,

    @SerialName(value = "song")
    val song: ComwitelokkmusicmodelsSong? = null,

    @SerialName(value = "release")
    val release: ComwitelokkmusicmodelsShortRelease? = null,

    @SerialName(value = "artist")
    val artist: ComwitelokkmusicmodelsShortArtist? = null,

    @SerialName(value = "playlist")
    val playlist: ComwitelokkmusicmodelsShortPlaylist? = null

) {


}

