/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.witelokk.musicapp.api.models

import com.witelokk.musicapp.api.models.ComwitelokkmusicmodelsShortArtist

import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * 
 *
 * @param count 
 * @param artists 
 * @param names 
 */
@Serializable

data class ComwitelokkmusicmodelsShortArtists (

    @SerialName(value = "count")
    val count: kotlin.Int,

    @SerialName(value = "artists")
    val artists: kotlin.collections.List<ComwitelokkmusicmodelsShortArtist>,

    @SerialName(value = "names")
    val names: kotlin.String

) {


}

