/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.witelokk.musicapp.api.models

import com.witelokk.musicapp.api.models.Releases

import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * 
 *
 * @param title 
 * @param titleRu 
 * @param releases 
 */
@Serializable

data class HomeScreenLayoutCompanionSection (

    @SerialName(value = "title")
    val title: kotlin.String,

    @SerialName(value = "title_ru")
    val titleRu: kotlin.String,

    @SerialName(value = "releases")
    val releases: Releases

) {


}

