/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.witelokk.musicapp.api.models

import com.witelokk.musicapp.api.models.ArtistsSummary
import com.witelokk.musicapp.api.models.HomeScreenLayoutCompanionSection
import com.witelokk.musicapp.api.models.PlaylistsSummary

import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * 
 *
 * @param playlists 
 * @param followedArtists 
 * @param sections 
 */
@Serializable

data class HomeScreenLayout (

    @SerialName(value = "playlists")
    val playlists: PlaylistsSummary,

    @SerialName(value = "followedArtists")
    val followedArtists: ArtistsSummary,

    @SerialName(value = "sections")
    val sections: kotlin.collections.List<HomeScreenLayoutCompanionSection>

) {


}

