/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.witelokk.musicapp.api.models

import com.witelokk.musicapp.api.models.Songs

import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * 
 *
 * @param id 
 * @param name 
 * @param songsCount 
 * @param songs 
 * @param coverUrl 
 */
@Serializable

data class Playlist (

    @SerialName(value = "id")
    val id: kotlin.String,

    @SerialName(value = "name")
    val name: kotlin.String,

    @SerialName(value = "songs_count")
    val songsCount: kotlin.Int,

    @SerialName(value = "songs")
    val songs: Songs,

    @SerialName(value = "cover_url")
    val coverUrl: kotlin.String? = null

) {


}

