/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.witelokk.musicapp.api.models

import com.witelokk.musicapp.api.models.ArtistsSummary

import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * 
 *
 * @param id 
 * @param name 
 * @param type 
 * @param releasedAt 
 * @param artists 
 * @param coverUrl 
 */
@Serializable

data class ReleaseSummary (

    @SerialName(value = "id")
    val id: kotlin.String,

    @SerialName(value = "name")
    val name: kotlin.String,

    @SerialName(value = "type")
    val type: kotlin.String,

    @SerialName(value = "released_at")
    val releasedAt: kotlin.String,

    @SerialName(value = "artists")
    val artists: ArtistsSummary,

    @SerialName(value = "cover_url")
    val coverUrl: kotlin.String? = null

) {


}

