/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.witelokk.musicapp.api.models

import com.witelokk.musicapp.api.models.SearchResultItem

import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * 
 *
 * @param query 
 * @param page 
 * @param limit 
 * @param total 
 * @param results 
 */
@Serializable

data class SearchResult (

    @SerialName(value = "query")
    val query: kotlin.String,

    @SerialName(value = "page")
    val page: kotlin.Int,

    @SerialName(value = "limit")
    val limit: kotlin.Int,

    @SerialName(value = "total")
    val total: kotlin.Int,

    @SerialName(value = "results")
    val results: kotlin.collections.List<SearchResultItem>

) {


}

