/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.witelokk.musicapp.api.models

import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName

/**
 * 
 *
 * @param type 
 * @param song 
 * @param release 
 * @param artist 
 * @param playlist 
 */
@Serializable

data class SearchResultItem (

    @SerialName(value = "type")
    val type: kotlin.String,

    @SerialName(value = "song")
    val song: Song? = null,

    @SerialName(value = "release")
    val release: ReleaseSummary? = null,

    @SerialName(value = "artist")
    val artist: ArtistSummary? = null,

    @SerialName(value = "playlist")
    val playlist: PlaylistSummary? = null

) {


}

