/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.witelokk.musicapp.api.models

import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName

/**
 * 
 *
 * @param id 
 * @param name 
 * @param isFavorite 
 * @param durationSeconds 
 * @param artists 
 * @param streamUrl 
 * @param coverUrl 
 */
@Serializable

data class Song (

    @SerialName(value = "id")
    val id: kotlin.String,

    @SerialName(value = "name")
    val name: kotlin.String,

    @SerialName(value = "is_favorite")
    val isFavorite: kotlin.Boolean,

    @SerialName(value = "duration_seconds")
    val durationSeconds: kotlin.Int,

    @SerialName(value = "artists")
    val artists: kotlin.collections.List<ArtistSummary>,

    @SerialName(value = "stream_url")
    val streamUrl: kotlin.String,

    @SerialName(value = "cover_url")
    val coverUrl: kotlin.String? = null

) {


}

