/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.witelokk.musicapp.api.apis

import com.witelokk.musicapp.api.models.Error
import com.witelokk.musicapp.api.models.SearchResponse

import com.witelokk.musicapp.api.infrastructure.*
import io.ktor.client.HttpClient
import io.ktor.client.HttpClientConfig
import io.ktor.client.request.forms.formData
import io.ktor.client.engine.HttpClientEngine
import kotlinx.serialization.json.Json
import io.ktor.http.ParametersBuilder
import io.ktor.http.Headers
import io.ktor.http.HttpHeaders
import io.ktor.http.ContentType
import io.ktor.http.content.PartData
import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

open class SearchApi : ApiClient {

    constructor(
        baseUrl: String = ApiClient.BASE_URL,
        httpClientEngine: HttpClientEngine? = null,
        httpClientConfig: ((HttpClientConfig<*>) -> Unit)? = null,
        jsonSerializer: Json = ApiClient.JSON_DEFAULT
    ) : super(baseUrl = baseUrl, httpClientEngine = httpClientEngine, httpClientConfig = httpClientConfig, jsonBlock = jsonSerializer)

    constructor(
        baseUrl: String,
        httpClient: HttpClient
    ): super(baseUrl = baseUrl, httpClient = httpClient)


    /**
     * enum for parameter type
     */
    @Serializable
    enum class TypeSearch(val value: kotlin.String) {
        
        @SerialName(value = "song")
        song("song"),
        
        @SerialName(value = "release")
        release("release"),
        
        @SerialName(value = "artist")
        artist("artist"),
        
        @SerialName(value = "playlist")
        playlist("playlist")
        
    }

    /**
     * Search songs, artists, releases and playlists
     * 
     * @param q 
     * @param type  (optional)
     * @param page  (optional, default to 1)
     * @param limit  (optional, default to 20)
     * @return SearchResponse
     */
    @Suppress("UNCHECKED_CAST")
    open suspend fun search(q: kotlin.String, type: TypeSearch? = null, page: kotlin.Int? = 1, limit: kotlin.Int? = 20): HttpResponse<SearchResponse> {

        val localVariableAuthNames = listOf<String>("bearerAuth")

        val localVariableBody = 
            io.ktor.client.utils.EmptyContent

        val localVariableQuery = mutableMapOf<String, List<String>>()
        q?.apply { localVariableQuery["q"] = listOf("$q") }
        type?.apply { localVariableQuery["type"] = listOf("${ type.value }") }
        page?.apply { localVariableQuery["page"] = listOf("$page") }
        limit?.apply { localVariableQuery["limit"] = listOf("$limit") }
        val localVariableHeaders = mutableMapOf<String, String>()

        val localVariableConfig = RequestConfig<kotlin.Any?>(
            RequestMethod.GET,
            "/search",
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = true,
        )

        return request(
            localVariableConfig,
            localVariableBody,
            localVariableAuthNames
        ).wrap()
    }


}
